//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipProblem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public long id { get; set; }
        public Nullable<long> country_id { get; set; }
        public Nullable<long> league_id { get; set; }
        public string season { get; set; }
        public Nullable<long> stage { get; set; }
        public string date { get; set; }
        public Nullable<long> match_api_id { get; set; }
        public Nullable<long> home_team_api_id { get; set; }
        public Nullable<long> away_team_api_id { get; set; }
        public Nullable<long> home_team_goal { get; set; }
        public Nullable<long> away_team_goal { get; set; }
        public Nullable<long> home_player_X1 { get; set; }
        public Nullable<long> home_player_X2 { get; set; }
        public Nullable<long> home_player_X3 { get; set; }
        public Nullable<long> home_player_X4 { get; set; }
        public Nullable<long> home_player_X5 { get; set; }
        public Nullable<long> home_player_X6 { get; set; }
        public Nullable<long> home_player_X7 { get; set; }
        public Nullable<long> home_player_X8 { get; set; }
        public Nullable<long> home_player_X9 { get; set; }
        public Nullable<long> home_player_X10 { get; set; }
        public Nullable<long> home_player_X11 { get; set; }
        public Nullable<long> away_player_X1 { get; set; }
        public Nullable<long> away_player_X2 { get; set; }
        public Nullable<long> away_player_X3 { get; set; }
        public Nullable<long> away_player_X4 { get; set; }
        public Nullable<long> away_player_X5 { get; set; }
        public Nullable<long> away_player_X6 { get; set; }
        public Nullable<long> away_player_X7 { get; set; }
        public Nullable<long> away_player_X8 { get; set; }
        public Nullable<long> away_player_X9 { get; set; }
        public Nullable<long> away_player_X10 { get; set; }
        public Nullable<long> away_player_X11 { get; set; }
        public Nullable<long> home_player_Y1 { get; set; }
        public Nullable<long> home_player_Y2 { get; set; }
        public Nullable<long> home_player_Y3 { get; set; }
        public Nullable<long> home_player_Y4 { get; set; }
        public Nullable<long> home_player_Y5 { get; set; }
        public Nullable<long> home_player_Y6 { get; set; }
        public Nullable<long> home_player_Y7 { get; set; }
        public Nullable<long> home_player_Y8 { get; set; }
        public Nullable<long> home_player_Y9 { get; set; }
        public Nullable<long> home_player_Y10 { get; set; }
        public Nullable<long> home_player_Y11 { get; set; }
        public Nullable<long> away_player_Y1 { get; set; }
        public Nullable<long> away_player_Y2 { get; set; }
        public Nullable<long> away_player_Y3 { get; set; }
        public Nullable<long> away_player_Y4 { get; set; }
        public Nullable<long> away_player_Y5 { get; set; }
        public Nullable<long> away_player_Y6 { get; set; }
        public Nullable<long> away_player_Y7 { get; set; }
        public Nullable<long> away_player_Y8 { get; set; }
        public Nullable<long> away_player_Y9 { get; set; }
        public Nullable<long> away_player_Y10 { get; set; }
        public Nullable<long> away_player_Y11 { get; set; }
        public Nullable<long> home_player_1 { get; set; }
        public Nullable<long> home_player_2 { get; set; }
        public Nullable<long> home_player_3 { get; set; }
        public Nullable<long> home_player_4 { get; set; }
        public Nullable<long> home_player_5 { get; set; }
        public Nullable<long> home_player_6 { get; set; }
        public Nullable<long> home_player_7 { get; set; }
        public Nullable<long> home_player_8 { get; set; }
        public Nullable<long> home_player_9 { get; set; }
        public Nullable<long> home_player_10 { get; set; }
        public Nullable<long> home_player_11 { get; set; }
        public Nullable<long> away_player_1 { get; set; }
        public Nullable<long> away_player_2 { get; set; }
        public Nullable<long> away_player_3 { get; set; }
        public Nullable<long> away_player_4 { get; set; }
        public Nullable<long> away_player_5 { get; set; }
        public Nullable<long> away_player_6 { get; set; }
        public Nullable<long> away_player_7 { get; set; }
        public Nullable<long> away_player_8 { get; set; }
        public Nullable<long> away_player_9 { get; set; }
        public Nullable<long> away_player_10 { get; set; }
        public Nullable<long> away_player_11 { get; set; }
        public string goal { get; set; }
        public string shoton { get; set; }
        public string shotoff { get; set; }
        public string foulcommit { get; set; }
        public string card { get; set; }
        public string cross { get; set; }
        public string corner { get; set; }
        public string possession { get; set; }
        public Nullable<decimal> B365H { get; set; }
        public Nullable<decimal> B365D { get; set; }
        public Nullable<decimal> B365A { get; set; }
        public Nullable<decimal> BWH { get; set; }
        public Nullable<decimal> BWD { get; set; }
        public Nullable<decimal> BWA { get; set; }
        public Nullable<decimal> IWH { get; set; }
        public Nullable<decimal> IWD { get; set; }
        public Nullable<decimal> IWA { get; set; }
        public Nullable<decimal> LBH { get; set; }
        public Nullable<decimal> LBD { get; set; }
        public Nullable<decimal> LBA { get; set; }
        public Nullable<decimal> PSH { get; set; }
        public Nullable<decimal> PSD { get; set; }
        public Nullable<decimal> PSA { get; set; }
        public Nullable<decimal> WHH { get; set; }
        public Nullable<decimal> WHD { get; set; }
        public Nullable<decimal> WHA { get; set; }
        public Nullable<decimal> SJH { get; set; }
        public Nullable<decimal> SJD { get; set; }
        public Nullable<decimal> SJA { get; set; }
        public Nullable<decimal> VCH { get; set; }
        public Nullable<decimal> VCD { get; set; }
        public Nullable<decimal> VCA { get; set; }
        public Nullable<decimal> GBH { get; set; }
        public Nullable<decimal> GBD { get; set; }
        public Nullable<decimal> GBA { get; set; }
        public Nullable<decimal> BSH { get; set; }
        public Nullable<decimal> BSD { get; set; }
        public Nullable<decimal> BSA { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual League League { get; set; }
    }
}
