//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipProblem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Attributes
    {
        public long id { get; set; }
        public Nullable<long> player_fifa_api_id { get; set; }
        public Nullable<long> player_api_id { get; set; }
        public string date { get; set; }
        public Nullable<long> overall_rating { get; set; }
        public Nullable<long> potential { get; set; }
        public string preferred_foot { get; set; }
        public string attacking_work_rate { get; set; }
        public string defensive_work_rate { get; set; }
        public Nullable<long> crossing { get; set; }
        public Nullable<long> finishing { get; set; }
        public Nullable<long> heading_accuracy { get; set; }
        public Nullable<long> short_passing { get; set; }
        public Nullable<long> volleys { get; set; }
        public Nullable<long> dribbling { get; set; }
        public Nullable<long> curve { get; set; }
        public Nullable<long> free_kick_accuracy { get; set; }
        public Nullable<long> long_passing { get; set; }
        public Nullable<long> ball_control { get; set; }
        public Nullable<long> acceleration { get; set; }
        public Nullable<long> sprint_speed { get; set; }
        public Nullable<long> agility { get; set; }
        public Nullable<long> reactions { get; set; }
        public Nullable<long> balance { get; set; }
        public Nullable<long> shot_power { get; set; }
        public Nullable<long> jumping { get; set; }
        public Nullable<long> stamina { get; set; }
        public Nullable<long> strength { get; set; }
        public Nullable<long> long_shots { get; set; }
        public Nullable<long> aggression { get; set; }
        public Nullable<long> interceptions { get; set; }
        public Nullable<long> positioning { get; set; }
        public Nullable<long> vision { get; set; }
        public Nullable<long> penalties { get; set; }
        public Nullable<long> marking { get; set; }
        public Nullable<long> standing_tackle { get; set; }
        public Nullable<long> sliding_tackle { get; set; }
        public Nullable<long> gk_diving { get; set; }
        public Nullable<long> gk_handling { get; set; }
        public Nullable<long> gk_kicking { get; set; }
        public Nullable<long> gk_positioning { get; set; }
        public Nullable<long> gk_reflexes { get; set; }
    }
}
