//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipProblem.Converter.Scheme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public long id { get; set; }
        public Nullable<long> player_api_id { get; set; }
        public string player_name { get; set; }
        public Nullable<long> player_fifa_api_id { get; set; }
        public string birthday { get; set; }
        public Nullable<long> height { get; set; }
        public Nullable<long> weight { get; set; }
    }
}
