//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipProblem.Converter.Scheme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public long id { get; set; }
        public Nullable<long> team_api_id { get; set; }
        public Nullable<long> team_fifa_api_id { get; set; }
        public string team_long_name { get; set; }
        public string team_short_name { get; set; }
    }
}
