//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipProblem.Converter.Scheme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_Attributes
    {
        public long id { get; set; }
        public Nullable<long> team_fifa_api_id { get; set; }
        public Nullable<long> team_api_id { get; set; }
        public string date { get; set; }
        public Nullable<long> buildUpPlaySpeed { get; set; }
        public string buildUpPlaySpeedClass { get; set; }
        public Nullable<long> buildUpPlayDribbling { get; set; }
        public string buildUpPlayDribblingClass { get; set; }
        public Nullable<long> buildUpPlayPassing { get; set; }
        public string buildUpPlayPassingClass { get; set; }
        public string buildUpPlayPositioningClass { get; set; }
        public Nullable<long> chanceCreationPassing { get; set; }
        public string chanceCreationPassingClass { get; set; }
        public Nullable<long> chanceCreationCrossing { get; set; }
        public string chanceCreationCrossingClass { get; set; }
        public Nullable<long> chanceCreationShooting { get; set; }
        public string chanceCreationShootingClass { get; set; }
        public string chanceCreationPositioningClass { get; set; }
        public Nullable<long> defencePressure { get; set; }
        public string defencePressureClass { get; set; }
        public Nullable<long> defenceAggression { get; set; }
        public string defenceAggressionClass { get; set; }
        public Nullable<long> defenceTeamWidth { get; set; }
        public string defenceTeamWidthClass { get; set; }
        public string defenceDefenderLineClass { get; set; }
    }
}
